# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pizza',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pizzas.Pizza'),
        ),
    ]
