# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20170524_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pizza',
        ),
        migrations.AddField(
            model_name='comment',
            name='pizza',
            field=models.ManyToManyField(related_name='comments', to='pizzas.Pizza'),
        ),
    ]
